### ISSUE TITLE
Add readme for installing and testing the project

### ISSUE THREAD

**Issue by ayat0110** [sandrosmarzaro/udp-chat#1]
Can you explain how to install and test the project?

**Comment by sandrosmarzaro** [comment]
Sure!

### Required dependencies:

-      [Python 3](https://www.python.org/downloads/)

-     [Mininet Wifi](https://github.com/intrig-unicamp/mininet-wifi) 

### Application
The project proposes a simple chat room where users connect to the server using their _IP_ and communicate via _UDP_ protocol and _JSON_ packets. After a successful connection, it is possible to request entry into a room, send messages to other users in it, and even leave that room.

### Code structure 
The project has three main files:

-     _topology.py_: Script that starts the prototype network using Mininet, containing 4 hosts, 1 server, and 1 switch, all connected to each other.

-     _server.py_: Code of the application that listens on the UDP protocol on an assigned port, receiving _JSON_ requests and redirecting them to specific functions.

-     _client.py_: Code run by users who can send JSON messages to enter a room, send messages to everyone in that room, and leave it.

### Observations
Note that this project is a simple program running locally on the same machine using a library to simulate different machines communicating. It is possible to run it in a different environment with some adjustments to the connection variables.
Some errors were not handled, such as cases of sudden exits from the room, where the in-memory list of participants is not updated, resulting in messages being sent to non-existent participants.

**Comment by ayat0110** [comment]
Thank you for the response and explanation!
